steps:
- name: '3.9.6-eclipse-temurin-21'
  entrypoint: mvn
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/${PROJECT_ID}/example-spring-image-repo/hello-api:latest', '.']


images:
- 'us-east1-docker.pkg.dev/${PROJECT_ID}/example-spring-image-repo/hello-api:latest'


options:
  logging: CLOUD_LOGGING_ONLY