steps:
- name: 'maven:3.9.6-eclipse-temurin-21'
  entrypoint: mvn
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/${PROJECT_ID}/ar-the-playground/hello-api:${SHORT_SHA}', '.']


images:
- 'us-east1-docker.pkg.dev/${PROJECT_ID}/ar-the-playground/hello-api:${SHORT_SHA}'


options:
  logging: CLOUD_LOGGING_ONLY